### ISSUE TITLE
UI: Improve responsive layout

### ISSUE THREAD

**Issue by fbrandel** [AOEpeople/aoepeople.github.io#15]
The layout is not responsive and can't be read properly on mobile devices.

![AOE_OpenSource](https://user-images.githubusercontent.com/201162/158351418-264702e7-172b-4b25-8619-49ebdf1b1db6.png)

**TODOs**
- [x] Add "meta"-Tag for "viewport"
- [x] Improve section "AOE People"
- [x] Improve section "AOE Articles"
- [x] Improve Footer
- [x] Improve Detail Page

**Comment by resah** [comment]
@bastianccm With the latest pull request merged the rest of the tasks should be done. Can we close the issue or do you thing there is something still open?
