### ISSUE TITLE
Incorporate Lighthouse findings

### ISSUE THREAD

**Issue by d738** [AOEpeople/aoepeople.github.io#24]
If you check the website with Lighthouse, you will find some points that might be worth a look.
I have attached the report here as a PDF and list some points below.

OPPORTUNITIES
- [x] #26 Properly size images: Serve images that are appropriately-sized to save cellular data and improve load time.
- [x] #26 Serve images in next-gen formats

NAMES AND LABELS
- [x] #28 Image elements do not have [alt] attributes: These are opportunities to improve the semantics of the controls in your application. This may enhance the experience for users of assistive technology, like a screen reader.

MOBILE FRIENDLY
- [x] #29 Does not have a <meta name="viewport"> tag with width or initial-scale: A `<meta name="viewport">` not only optimizes your app for mobile screen sizes, but also prevents a 300 millisecond delay to user input.

CONTENT BEST PRACTICES
- [x] #30 Document does not have a meta description: Meta descriptions may be included in search results to concisely summarize page content.

[20220317_LighthouseFindings.pdf](https://github.com/AOEpeople/aoepeople.github.io/files/8283239/20220317_LighthouseFindings.pdf)

**Comment by bastianccm** [comment]
All resolved, Lighthouse still suggests to cache static files, but that's currently not possible, see #27

**Comment by bastianccm** [comment]
![Screenshot 2022-03-20 at 20 03 11](https://user-images.githubusercontent.com/1145424/159178337-9e714f01-76df-4d5b-854e-ef3fbe7072b3.png)

This looks ok :)
